
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Recopila comentarios de los usuarios sobre la precisión de la traducción.
 *
 * - collectTranslationFeedback - Una función para recopilar comentarios sobre la precisión de la traducción.
 * - CollectTranslationFeedbackInput - El tipo de entrada para la función collectTranslationFeedback.
 * - CollectTranslationFeedbackOutput - El tipo de retorno para la función collectTranslationFeedback.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CollectTranslationFeedbackInputSchema = z.object({
  originalText: z.string().describe('El texto original que fue traducido.'),
  translatedText: z.string().describe('El texto traducido.'),
  feedback: z.enum(['thumbs_up', 'thumbs_down']).describe('Comentarios del usuario sobre la traducción.'),
});
export type CollectTranslationFeedbackInput = z.infer<typeof CollectTranslationFeedbackInputSchema>;

const CollectTranslationFeedbackOutputSchema = z.object({
  success: z.boolean().describe('Indica si los comentarios se registraron correctamente.'),
  message: z.string().optional().describe('Un mensaje que indica el estado del proceso de retroalimentación.'),
});
export type CollectTranslationFeedbackOutput = z.infer<typeof CollectTranslationFeedbackOutputSchema>;

export async function collectTranslationFeedback(input: CollectTranslationFeedbackInput): Promise<CollectTranslationFeedbackOutput> {
  return collectTranslationFeedbackFlow(input);
}

const collectTranslationFeedbackFlow = ai.defineFlow(
  {
    name: 'collectTranslationFeedbackFlow',
    inputSchema: CollectTranslationFeedbackInputSchema,
    outputSchema: CollectTranslationFeedbackOutputSchema,
  },
  async input => {
    // Simulate saving feedback to a database or other storage.
    // In a real application, this would involve writing to a database.
    console.log('Comentarios recibidos:', input);

    // For now, just return a success message.
    return {
      success: true,
      message: 'Comentarios registrados correctamente.',
    };
  }
);
