
// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Newspaper } from 'lucide-react';

interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  imageUrl: string;
  dataAiHint: string;
  publicationDate: string;
  source: string;
  articleUrl: string; // Placeholder for full article link
}

const newsArticles: NewsArticle[] = [
  {
    id: 'new-species-discovery-2025',
    title: 'Descubren Nueva Especie Bioluminiscente en la Fosa de las Marianas',
    summary: 'Científicos anuncian el hallazgo de una nueva especie de pez abisal que emite una luz azul intensa, adaptada a la oscuridad total de las profundidades marinas. El descubrimiento abre nuevas vías de investigación sobre la vida en condiciones extremas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'deep sea fish',
    publicationDate: '25 de Febrero, 2025',
    source: 'Instituto Oceanográfico Global',
    articleUrl: '/news/new-species-discovery-2025',
  },
  {
    id: 'plastic-cleanup-pacific-2025',
    title: 'Innovador Sistema de Limpieza de Plásticos Muestra Resultados Prometedores en el Pacífico',
    summary: 'Un nuevo sistema autónomo de recolección de plásticos ha superado las pruebas iniciales, retirando varias toneladas de desechos del Gran Parche de Basura del Pacífico en su primer mes de operación.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ocean cleanup',
    publicationDate: '10 de Marzo, 2025',
    source: 'Tecnología Marina Limpia Hoy',
    articleUrl: '/news/plastic-cleanup-pacific-2025',
  },
  {
    id: 'coral-reef-recovery-caribbean-2025',
    title: 'Arrecifes de Coral del Caribe Muestran Signos de Recuperación Gracias a Esfuerzos de Restauración',
    summary: 'Proyectos de restauración de coral a gran escala en el Caribe están dando frutos, con un notable aumento en la cobertura de coral vivo y la biodiversidad asociada, según un estudio reciente.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coral reef restoration',
    publicationDate: '5 de Abril, 2025',
    source: 'Conservación Coralina Internacional',
    articleUrl: '/news/coral-reef-recovery-caribbean-2025',
  },
  {
    id: 'ocean-acidification-impact-2025',
    title: 'Nuevo Estudio Revela Impactos Acelerados de la Acidificación Oceánica en Moluscos',
    summary: 'Una investigación publicada hoy advierte que la acidificación de los océanos está afectando a las poblaciones de moluscos a un ritmo más rápido de lo previsto, amenazando las cadenas alimentarias marinas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ocean acidification',
    publicationDate: '18 de Mayo, 2025',
    source: 'Revista Científica Marina',
    articleUrl: '/news/ocean-acidification-impact-2025',
  },
];

export default function NewsPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <div className="inline-flex items-center justify-center bg-primary/10 p-3 rounded-full mb-4">
          <Newspaper className="h-10 w-10 text-primary" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Noticias del Océano
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Mantente al día con los últimos acontecimientos y descubrimientos del mundo marino.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-1"> {/* Single column for better readability of news items */}
        {newsArticles.map((article) => (
          <Card
            key={article.id}
            className="flex flex-col md:flex-row rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl overflow-hidden"
          >
            <div className="md:w-1/3 h-48 md:h-auto overflow-hidden">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={article.imageUrl}
                alt={article.title}
                className="w-full h-full object-cover transition-transform duration-300 hover:scale-105"
                data-ai-hint={article.dataAiHint}
              />
            </div>
            <div className="md:w-2/3 flex flex-col">
              <CardHeader className="p-6">
                <CardTitle className="text-xl font-semibold hover:text-primary transition-colors">
                  <Link href={article.articleUrl}>{article.title}</Link>
                </CardTitle>
                <CardDescription className="text-xs text-muted-foreground pt-1">
                  Publicado el {article.publicationDate} por {article.source}
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-grow p-6 pt-0">
                <p className="text-sm text-muted-foreground line-clamp-3">
                  {article.summary}
                </p>
              </CardContent>
              <CardFooter className="p-6 pt-0">
                <Button asChild variant="outline" size="sm">
                  <Link href={article.articleUrl}>Leer Más</Link>
                </Button>
              </CardFooter>
            </div>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <Button asChild variant="link">
          <Link href="/">Volver a la Página Principal</Link>
        </Button>
      </div>
    </div>
  );
}
