
// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { ShoppingBag, Sparkles, Waves, Hand, Recycle, Leaf, Shirt } from 'lucide-react';

interface ProductCategory {
  id: string;
  name: string;
  description: string;
  icon: React.ElementType;
  imageUrl: string;
  dataAiHint: string;
  categoryPageUrl: string;
}

const productCategories: ProductCategory[] = [
  {
    id: 'shampoos',
    name: 'Champús Sólidos y Recargables',
    description: 'Reduce los residuos plásticos con champús sólidos o opciones recargables amigables con el océano.',
    icon: Sparkles, // Icon for shampoos
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'shampoo bar',
    categoryPageUrl: '/products/shampoos',
  },
  {
    id: 'conditioners',
    name: 'Acondicionadores Naturales',
    description: 'Acondicionadores con ingredientes biodegradables que no dañan la vida marina y vienen en empaques sostenibles.',
    icon: Waves, // Icon for conditioners
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'natural conditioner',
    categoryPageUrl: '/products/conditioners',
  },
  {
    id: 'soaps',
    name: 'Jabones Artesanales y Ecológicos',
    description: 'Jabones hechos con ingredientes naturales, sin microplásticos y con empaques mínimos o compostables.',
    icon: Hand, // Icon for soaps
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'artisan soap',
    categoryPageUrl: '/products/soaps',
  },
  {
    id: 'plastic-wood',
    name: 'Madera Plástica Reciclada',
    description: 'Alternativa duradera a la madera tradicional, hecha de plásticos reciclados, ideal para muebles de exterior y construcción.',
    icon: Recycle, // Icon for plastic wood
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'recycled plastic',
    categoryPageUrl: '/products/plastic-wood',
  },
  {
    id: 'beeswax-wraps',
    name: 'Envoltorios de Cera de Abeja',
    description: 'Reutilizables y biodegradables, estos envoltorios son una excelente alternativa al film plástico para conservar alimentos.',
    icon: Leaf, // Icon for beeswax wraps
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'beeswax wrap',
    categoryPageUrl: '/products/beeswax-wraps',
  },
  {
    id: 'eco-swimwear',
    name: 'Trajes de Baño Ecológicos',
    description: 'Hechos con fibras recicladas de redes de pesca y otros plásticos recuperados del océano, apoyando la moda sostenible.',
    icon: Shirt, // Icon for eco-friendly swimwear
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'eco swimwear',
    categoryPageUrl: '/products/eco-swimwear',
  },
];

export default function SustainableProductsPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <div className="inline-flex items-center justify-center bg-primary/10 p-3 rounded-full mb-4">
          <ShoppingBag className="h-10 w-10 text-primary" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Productos Sostenibles para el Océano
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Descubre alternativas ecológicas que ayudan a proteger nuestros mares y su biodiversidad.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {productCategories.map((category, index) => (
          <Card
            key={category.id}
            className="flex flex-col rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-5 duration-500 ease-out"
            style={{ animationDelay: `${index * 100}ms` }}
          >
            <div className="w-full h-48 overflow-hidden">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={category.imageUrl}
                alt={category.name}
                className="w-full h-full object-cover transition-transform duration-300 hover:scale-105"
                data-ai-hint={category.dataAiHint}
              />
            </div>
            <CardHeader className="p-6">
              <CardTitle className="text-xl font-semibold flex items-center">
                <category.icon className="h-6 w-6 mr-3 text-primary shrink-0" />
                {category.name}
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-grow p-6 pt-0">
              <p className="text-sm text-muted-foreground line-clamp-3">
                {category.description}
              </p>
            </CardContent>
            <CardFooter className="p-6 bg-muted/30">
              <Button asChild variant="outline" className="w-full">
                <Link href={category.categoryPageUrl}>Ver Productos</Link>
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <Button asChild variant="link">
          <Link href="/">Volver a la Página Principal</Link>
        </Button>
      </div>
    </div>
  );
}
