
// This is an autogenerated file from Firebase Studio.
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Crown, Zap } from "lucide-react";
import Link from "next/link";

interface PlanFeature {
  text: string;
  available: boolean;
}

interface Plan {
  id: string;
  title: string;
  description: string;
  price: string;
  pricePeriod: string;
  features: PlanFeature[];
  cta: string;
  highlight?: boolean;
  icon?: React.ReactNode;
}

const plans: Plan[] = [
  {
    id: "bronze",
    title: "Bronze Seahorse",
    description: "Get started with essential translation features.",
    price: "$5",
    pricePeriod: "/ month",
    features: [
      { text: "Up to 1,000 translations/month", available: true },
      { text: "Standard translation speed", available: true },
      { text: "Basic feedback history", available: true },
      { text: "Email support", available: true },
      { text: "Priority support", available: false },
      { text: "Access to new languages (beta)", available: false },
    ],
    cta: "Choose Bronze",
    icon: <CheckCircle className="h-6 w-6 text-primary" />,
  },
  {
    id: "silver",
    title: "Silver Dolphin",
    description: "More translations and faster performance.",
    price: "$15",
    pricePeriod: "/ month",
    features: [
      { text: "Up to 10,000 translations/month", available: true },
      { text: "Enhanced translation speed", available: true },
      { text: "Detailed feedback history", available: true },
      { text: "Priority email support", available: true },
      { text: "Priority support", available: true },
      { text: "Access to new languages (beta)", available: false },
    ],
    cta: "Choose Silver",
    highlight: true,
    icon: <Zap className="h-6 w-6 text-accent" />,
  },
  {
    id: "gold",
    title: "Gold Whale",
    description: "The ultimate translation experience for power users.",
    price: "$30",
    pricePeriod: "/ month",
    features: [
      { text: "Unlimited translations", available: true },
      { text: "Lightning-fast translation speed", available: true },
      { text: "Comprehensive feedback history & analytics", available: true },
      { text: "24/7 Priority support", available: true },
      { text: "Priority support", available: true },
      { text: "Early access to new languages (beta)", available: true },
    ],
    cta: "Choose Gold",
    icon: <Crown className="h-6 w-6 text-yellow-500" />,
  },
];

export default function PremiumPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Unlock Premium MTM Features
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Choose a plan that fits your needs and elevate your translation experience.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {plans.map((plan) => (
          <Card
            key={plan.id}
            className={`flex flex-col rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl ${
              plan.highlight ? "border-2 border-accent ring-2 ring-accent/50" : "border-border"
            }`}
          >
            <CardHeader className="p-6">
              <div className="flex items-center justify-between mb-2">
                <CardTitle className="text-2xl font-semibold">{plan.title}</CardTitle>
                {plan.icon}
              </div>
              <CardDescription className="text-sm text-muted-foreground h-10">
                {plan.description}
              </CardDescription>
            </CardHeader>
            <CardContent className="flex-grow p-6">
              <div className="mb-6">
                <span className="text-4xl font-extrabold text-foreground">{plan.price}</span>
                <span className="text-sm font-medium text-muted-foreground">{plan.pricePeriod}</span>
              </div>
              <ul className="space-y-3">
                {plan.features.map((feature, index) => (
                  <li key={index} className="flex items-center">
                    <CheckCircle
                      className={`h-5 w-5 mr-2 shrink-0 ${
                        feature.available ? "text-green-500" : "text-muted-foreground/50"
                      }`}
                    />
                    <span className={!feature.available ? "text-muted-foreground line-through" : ""}>
                      {feature.text}
                    </span>
                  </li>
                ))}
              </ul>
            </CardContent>
            <CardFooter className="p-6 bg-muted/30 rounded-b-xl">
              <Button
                className={`w-full text-lg py-3 ${
                  plan.highlight ? "bg-accent hover:bg-accent/90 text-accent-foreground" : ""
                }`}
                size="lg"
                asChild
              >
                <Link href={`/subscribe?plan=${plan.id}`}>{plan.cta}</Link>
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <p className="text-muted-foreground">
          Need a custom solution or have questions?{" "}
          <Link href="/contact" className="font-medium text-primary hover:underline">
            Contact Us
          </Link>
        </p>
      </div>
    </div>
  );
}
