
// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Star, MessageSquareText } from 'lucide-react'; // Added MessageSquareText for header

interface Review {
  id: string;
  userName: string;
  userAvatarUrl: string;
  dataAiHintAvatar: string;
  rating: number; // Number of stars (1-5)
  reviewText: string;
  reviewDate: string;
}

const reviewsData: Review[] = [
  {
    id: 'review1',
    userName: 'Explorador@ Marín@',
    userAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHintAvatar: 'diver avatar',
    rating: 5,
    reviewText: '¡MTM es increíble! He aprendido muchísimo sobre la vida marina y los esfuerzos de conservación. La sección de noticias siempre está actualizada. ¡Muy recomendable!',
    reviewDate: '15 de Abril, 2025',
  },
  {
    id: 'review2',
    userName: 'Científic@ Curios@',
    userAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHintAvatar: 'scientist avatar',
    rating: 4,
    reviewText: 'Una plataforma muy completa y bien diseñada. Los artículos de investigación son fascinantes y fáciles de entender. Me gustaría ver más interactividad en el futuro.',
    reviewDate: '22 de Marzo, 2025',
  },
  {
    id: 'review3',
    userName: 'Amante del Océano',
    userAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHintAvatar: 'ocean lover',
    rating: 5,
    reviewText: 'Me encantan los productos sostenibles que se muestran. ¡Ya he comprado varios! Es genial encontrar un lugar que promueva la conciencia oceánica de esta manera.',
    reviewDate: '10 de Mayo, 2025',
  },
  {
    id: 'review4',
    userName: 'Estudiante de Biología',
    userAvatarUrl: 'https://placehold.co/100x100.png',
    dataAiHintAvatar: 'student avatar',
    rating: 4,
    reviewText: 'Excelente recurso para mis estudios. La información sobre especies es detallada y las imágenes de referencia (aunque sean placeholders por ahora) son útiles. ¡Gracias!',
    reviewDate: '5 de Junio, 2025',
  },
];

const renderStars = (rating: number) => {
  const stars = [];
  for (let i = 0; i < 5; i++) {
    stars.push(
      <Star
        key={i}
        className={`h-5 w-5 ${i < rating ? 'text-yellow-400 fill-yellow-400' : 'text-muted-foreground/30'}`}
      />
    );
  }
  return stars;
};

export default function ReviewsPage() {
  // Calculate average rating (optional, for display)
  const totalRating = reviewsData.reduce((acc, review) => acc + review.rating, 0);
  const averageRating = reviewsData.length > 0 ? (totalRating / reviewsData.length).toFixed(1) : 0;

  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <div className="inline-flex items-center justify-center bg-primary/10 p-3 rounded-full mb-4">
          <MessageSquareText className="h-10 w-10 text-primary" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Opiniones de Nuestros Usuarios
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Descubre lo que nuestra comunidad piensa sobre MTM.
        </p>
      </header>

      {/* Optional: Display Average Rating */}
      <div className="mb-10 text-center">
        <h2 className="text-2xl font-semibold text-foreground">Calificación Promedio</h2>
        <div className="flex items-center justify-center mt-2">
          {renderStars(parseFloat(averageRating.toString()))}
          <span className="ml-2 text-2xl font-bold text-primary">{averageRating} / 5</span>
        </div>
        <p className="text-muted-foreground text-sm mt-1">Basado en {reviewsData.length} reseñas</p>
      </div>


      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {reviewsData.map((review, index) => (
          <Card
            key={review.id}
            className="flex flex-col rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl animate-in fade-in slide-in-from-bottom-5 duration-500 ease-out"
            style={{ animationDelay: `${index * 100}ms` }}
          >
            <CardHeader className="p-6 flex flex-row items-center gap-4">
              <Avatar className="h-12 w-12">
                <AvatarImage src={review.userAvatarUrl} alt={review.userName} data-ai-hint={review.dataAiHintAvatar} />
                <AvatarFallback>{review.userName.substring(0, 2)}</AvatarFallback>
              </Avatar>
              <div>
                <CardTitle className="text-lg font-semibold">{review.userName}</CardTitle>
                <div className="flex items-center mt-1">
                  {renderStars(review.rating)}
                </div>
              </div>
            </CardHeader>
            <CardContent className="flex-grow p-6 pt-0">
              <p className="text-sm text-muted-foreground italic">&quot;{review.reviewText}&quot;</p>
            </CardContent>
            <CardFooter className="p-6 pt-2 text-xs text-muted-foreground">
              Publicado el {review.reviewDate}
            </CardFooter>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <Button asChild variant="link">
          <Link href="/">Volver a la Página Principal</Link>
        </Button>
      </div>
    </div>
  );
}
