
// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Turtle, Star, Sparkles, VenetianMask, Whale } from 'lucide-react'; // Using VenetianMask for Mantis Shrimp as a placeholder

interface MarineAnimal {
  id: string;
  name: string;
  description: string;
  icon: React.ElementType;
  imageUrl: string;
  dataAiHint: string;
  detailsPageUrl: string;
}

const marineAnimals: MarineAnimal[] = [
  {
    id: 'sea-turtles',
    name: 'Tortugas Marinas',
    description: 'Sumérgete en el mundo de estas majestuosas criaturas marinas y su importancia en los ecosistemas oceánicos.',
    icon: Turtle,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sea turtle',
    detailsPageUrl: '/species/sea-turtles', // Placeholder link
  },
  {
    id: 'starfish',
    name: 'Estrellas de Mar',
    description: 'Descubre la increíble diversidad y las fascinantes adaptaciones de estos equinodermos.',
    icon: Star,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'starfish ocean',
    detailsPageUrl: '/species/starfish', // Placeholder link
  },
  {
    id: 'corals',
    name: 'Corales',
    description: 'Explora los vibrantes arrecifes de coral, los "bosques tropicales del mar", y su crucial papel ecológico.',
    icon: Sparkles, // Using Sparkles as a generic representation of coral beauty
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coral reef',
    detailsPageUrl: '/species/corals', // Placeholder link
  },
  {
    id: 'mantis-shrimp',
    name: 'Camarón Mantis',
    description: 'Conoce al camarón mantis, famoso por su poderosa pegada y su compleja visión.',
    icon: VenetianMask, // Placeholder icon, consider a more fitting one or custom SVG
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mantis shrimp',
    detailsPageUrl: '/species/mantis-shrimp', // Placeholder link
  },
  {
    id: 'whales',
    name: 'Ballenas',
    description: 'Aprende sobre los gigantes del océano, desde la ballena azul hasta las juguetonas jorobadas.',
    icon: Whale,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'whale ocean',
    detailsPageUrl: '/species/whales', // Placeholder link
  },
];

export default function SpeciesPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Explora las Especies Marinas
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Descubre la increíble diversidad de vida que habita en nuestros océanos.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {marineAnimals.map((animal) => (
          <Card
            key={animal.id}
            className="flex flex-col rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl overflow-hidden"
          >
            <div className="w-full h-48 overflow-hidden">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={animal.imageUrl}
                alt={animal.name}
                className="w-full h-full object-cover transition-transform duration-300 hover:scale-105"
                data-ai-hint={animal.dataAiHint}
              />
            </div>
            <CardHeader className="p-6">
              <CardTitle className="text-2xl font-semibold flex items-center">
                <animal.icon className="h-6 w-6 mr-2 text-primary" />
                {animal.name}
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-grow p-6 pt-0">
              <CardDescription className="text-sm text-muted-foreground">
                {animal.description}
              </CardDescription>
            </CardContent>
            <CardFooter className="p-6 bg-muted/30">
              <Button asChild variant="outline" className="w-full">
                <Link href={animal.detailsPageUrl}>Saber Más</Link>
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <Button asChild variant="link">
          <Link href="/">Volver a la Página Principal</Link>
        </Button>
      </div>
    </div>
  );
}
